### ISSUE TITLE
503 Service Unavailable "http://maven.tealiumiq.com/java/releases/com/tealium/java/1.3.2/java-1.3.2.jar"

### ISSUE THREAD

**Issue by ghost** [Tealium/tealium-java#15]
Below, I attempted to download the Tealium java-1.3.2.jar both through the Jenkins CI pipeline and via the terminal. Both methods resulted in the following error, and I have been unable to identify the root cause or a solution. What could be the issue here

Attempting to download using Jenkins CI pipeline:
```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not download java-1.3.2.jar (com.tealium:java:1.3.2)
      > Could not get resource 'http://maven.tealiumiq.com/java/releases/com/tealium/java/1.3.2/java-1.3.2.jar'.
         > Connection reset
```

Attempting to download using the terminal:
```
 wget http://maven.tealiumiq.com/java/releases/com/tealium/java/1.3.2/java-1.3.2.jar
--2024-06-18 08:24:20--  http://maven.tealiumiq.com/java/releases/com/tealium/java/1.3.2/java-1.3.2.jar
Resolving maven.tealiumiq.com (maven.tealiumiq.com)... 99.86.229.75, 99.86.229.38, 99.86.229.8, ...
Connecting to maven.tealiumiq.com (maven.tealiumiq.com)|99.86.229.75|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2024-06-18 08:24:20 ERROR 503: Service Unavailable.
```

**Comment by jameskeith** [comment]
@afer4152 - apologies, I've only just seen this issue. Are you still seeing problems downloading from our Maven repository?

I've had a quick look, but don't see any reported outages in our system, or the system of the relevant service provider that would explain this as an issue. 
To confirm, I have been able to successfully download that file using a browser, and `wget` 

Although I'm not sure it'll be responsible for the 503, I would recommend updating to use the `https` version of that URL. I know some systems can be very fussy about downloading insecure content.

**Comment by ghost** [comment]
> @afer4152 - apologies, I've only just seen this issue. Are you still seeing problems downloading from our Maven repository?
> 
> I've had a quick look, but don't see any reported outages in our system, or the system of the relevant service provider that would explain this as an issue. To confirm, I have been able to successfully download that file using a browser, and `wget`
> 
> Although I'm not sure it'll be responsible for the 503, I would recommend updating to use the `https` version of that URL. I know some systems can be very fussy about downloading insecure content.

This is work for us. Thank you!
