### ISSUE TITLE
Track event with mixed fields from previous event

### ISSUE THREAD

**Issue by ylevin** [Tealium/tealium-java#7]
If track multiple events sequentially and some fields absent in current Udo, but exists in previous tracked Udo, they mixed in a new event. To avoid this behavior it needs to remove previous field(s) from cached udo: `tealium.getDataManager.getPersistentData.remove(fieldName)`. This behavior seems to be unobvious.

**Comment by jameskeith** [comment]
Hi @ylevin 
The persistentData object is used for key-values that should persist across launches of your application - there will be a few keys in there by default used by Tealium. For every event that is tracked, the persistent Udo will be added to the event payload along with other common data (volatile data, Tealium account/profile/data source etc)

I don't believe that any data from previous events is expected to be saved into the persistent data, unless this has been explicitly requested by yourself.
Is it possible to get more information on which keys you are seeing in consecutive events that shouldn't be there?

**Comment by ylevin** [comment]
1) Here https://github.com/Tealium/tealium-java/blob/master/src/main/java/com/tealium/Tealium.java#L300. Load cache
2) Here https://github.com/Tealium/tealium-java/blob/master/src/main/java/com/tealium/Tealium.java#L320 add fields from udo into cache map
3) But never clean fields from cached udo, if next tracked event missed some fields, it still exists in cached udo

payloadData is not a new map, it's cache

**Comment by ylevin** [comment]
PR: https://github.com/Tealium/tealium-java/pull/8

**Comment by jameskeith** [comment]
Thanks for the information @ylevin - I had read your original message the wrong way round, but I see what you're getting at now. I'll raise a task internally to get this addressed and released - thanks for submitting the PR already.

**Comment by jameskeith** [comment]
This should now be fixed in v1.3.1 available on our maven repository.
Thanks for bringing it to our attention @ylevin
